language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_4ff52b14fc38_key -iv $encrypted_4ff52b14fc38_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - wget -qO- https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz | tar xz
  - ls google-cloud-sdk
  - ./google-cloud-sdk/install.sh -q
  - tar -xzf credentials.tar.gz

before_script:
  - gcloud config set project spry-firefly-206711
  - gcloud auth activate-service-account --key-file $TRAVIS_BUILD_DIR/travis-secret.json

script:
  - yarn test
  - yarn build
  - tar -cvf app.tar build/
  - gcloud compute scp --zone europe-west1-b ./app.tar knuca-database:~/app.tar
  - gcloud compute ssh knuca-database --zone europe-west1-b --force-key-file-overwrite -- 'ls &&
    sudo rm -rf /var/www/knuca-web/html/* &&
    sudo tar -xvf ~/app.tar -C /var/www/knuca-web/html/ --strip-components=1 &&
    sudo nginx -s reload'
