language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test
  - yarn build
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master