language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules

script:
  - yarn test
  - yarn build
  - tar -cvf ./docker/app.tar build/
  - cd docker
  - docker build . -t knuca-image
  - docker tag knuca-image $DOCKER_HUB_USERNAME/knuca-web:$TRAVIS_BUILD_NUMBER
  - docker tag knuca-image $DOCKER_HUB_USERNAME/knuca-web:latest
  - docker push $DOCKER_HUB_USERNAME/knuca-web:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_HUB_USERNAME/knuca-web:latest;
